// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUNm22XMOfpVpUu9VeIhYdeDBpZPYNUM',
    appId: '1:216493554082:web:e1c497339d59689ec7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    authDomain: 'nuduwawithflutter.firebaseapp.com',
    storageBucket: 'nuduwawithflutter.appspot.com',
    measurementId: 'G-WJL0S20HJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgX5oQFy6NZ1n1bIfmfN9AhbX6uJ5NDo',
    appId: '1:216493554082:android:76dbe56a07055387c7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    storageBucket: 'nuduwawithflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHvP6_SuGV02ojlvO9qMBMYcFfuApPt08',
    appId: '1:216493554082:ios:a6b2de1c74dab0fcc7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    storageBucket: 'nuduwawithflutter.appspot.com',
    iosClientId: '216493554082-fs8trvf8s551emgp9e8be0esmia89lo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuduwaWithFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHvP6_SuGV02ojlvO9qMBMYcFfuApPt08',
    appId: '1:216493554082:ios:a6b2de1c74dab0fcc7dafb',
    messagingSenderId: '216493554082',
    projectId: 'nuduwawithflutter',
    storageBucket: 'nuduwawithflutter.appspot.com',
    iosClientId: '216493554082-fs8trvf8s551emgp9e8be0esmia89lo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuduwaWithFlutter',
  );
}
